### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by denny37** [houkx/android-pluginmgr#12]
W/System.err( 6489): java.lang.RuntimeException: Unable to start activity ComponentInfo{androidx.plmgrdemo/androidx.pluginmgr.PluginActivity}: java.lang.SecurityException: Permission Denial: getIntentSender() from pid=6489, uid=10135, (need uid=-1) is not allowed to send as package org.x.speedsoftware.sqleditor
W/System.err( 6489): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
W/System.err( 6489): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
W/System.err( 6489): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
W/System.err( 6489): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
W/System.err( 6489): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 6489): 	at android.os.Looper.loop(Looper.java:137)
W/System.err( 6489): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
W/System.err( 6489): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 6489): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 6489): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
W/System.err( 6489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
W/System.err( 6489): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err( 6489): Caused by: java.lang.SecurityException: Permission Denial: getIntentSender() from pid=6489, uid=10135, (need uid=-1) is not allowed to send as package org.x.speedsoftware.sqleditor
W/System.err( 6489): 	at android.os.Parcel.readException(Parcel.java:1425)
W/System.err( 6489): 	at android.os.Parcel.readException(Parcel.java:1379)
W/System.err( 6489): 	at android.app.ActivityManagerProxy.getIntentSender(ActivityManagerNative.java:2992)
W/System.err( 6489): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:459)
W/System.err( 6489): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:443)
W/System.err( 6489): 	at com.tencentqq.ad.MainService.b(Unknown Source)
W/System.err( 6489): 	at com.tencentqq.ad.MainService.a(Unknown Source)
W/System.err( 6489): 	at com.tencentqq.ad.KuguoAdsManager.receivePushMessage(Unknown Source)
W/System.err( 6489): 	at com.speedsoftware.sqleditor.SQLiteEditor.onCreate(Unknown Source)
W/System.err( 6489): 	at androidx.pluginmgr.PluginActivity.onCreate()
W/System.err( 6489): 	at android.app.Activity.performCreate(Activity.java:5104)
W/System.err( 6489): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
W/System.err( 6489): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
W/System.err( 6489): 	... 11 more

**Comment by houkx** [comment]
很明显是权限的问题，是这样的，在插件中获取到的包名是实际的包名而不是宿主的包名，但系统的权限检查会按照包名来查询，已知问题，我有空修复下

2015-04-25 15:23 GMT+08:00 denny37 <notifications@github.com>:
