### ISSUE TITLE
有些apk作为插件会报 androidx.pluginmgr.PluginActivity}: java.lang.ClassNotFoundException: 

### ISSUE THREAD

**Issue by gzu-liyujiang** [houkx/android-pluginmgr#14]
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{****/androidx.pluginmgr.PluginActivity}: java.lang.ClassNotFoundException: androidx.pluginmgr.PluginActivity
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2116)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread.access$800(ActivityThread.java:141)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:102)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:136)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:5047)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at java.lang.reflect.Method.invokeNative(Native Method)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Method.java:515)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at dalvik.system.NativeStart.main(Native Method)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               Caused by: java.lang.ClassNotFoundException: androidx.pluginmgr.PluginActivity
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at java.lang.ClassLoader.findClass(ClassLoader.java:332)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at androidx.pluginmgr.FrameworkClassLoader.loadClass(FrameworkClassLoader.java:65)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2107)
05-17 00:37:52.223 31466 31466 E   AndroidRuntime                               ... 11 more

**Comment by houkx** [comment]
ClassNotFoundException 不是真正的原因
