### ISSUE TITLE
android4.0 插件内启动activity报错

### ISSUE THREAD

**Issue by ltg-13** [houkx/android-pluginmgr#17]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.plugindemo/com.example.plugindemo.DetailActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1526)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1386)
	at android.app.Activity.startActivityForResult(Activity.java:3190)
	at com.example.plugindemo.MainActivity.onClick(MainActivity.java:47)
	at android.view.View.performClick(View.java:3511)
	at android.view.View$PerformClick.run(View.java:14105)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dezhi1231** [comment]
想问下怎么解决的了？
